# Generated by Django 5.0.6 on 2024-08-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=20)),
                ('job_industry', models.CharField(max_length=20)),
                ('job_country', models.CharField(max_length=20)),
                ('job_description', models.TextField()),
            ],
        ),
    ]
